### ISSUE TITLE
Connect a new tag to call a custom class

### ISSUE THREAD

**Issue by adenine** [quinkennedy/ZineBuilder#4]

**Comment by quinkennedy** [comment]
to support a new tag type:

1. create a class that extends WorkshopBox: `public class ThreeDee extends WorkshopBox{}`
2. implement the virtual functions of WorkshopBox:
   * `public Rectangle render(XML xml, Rectangle rect, PGraphics pg, VarService vars, boolean debug){...}`
   * `public boolean isResizable(){...}`
3. register the class in WorkshopBoxes: `boxes.put("threedee", zineBuilder.new ThreeDee());`

now you can use the tag `<threedee attr="custom">some fill text?</threedee>` in _zine.xml_
